### ISSUE TITLE
Question abt star image generation

### ISSUE THREAD

**Issue by JyKlub** [UWCubeSat/lost#132]
Hi! It's me again lol. I have been doing a few experiments with star image generation as well as attitude identification, one problem i realized and encountered is that in many cases the star position x&y calculated in the pixel coordinate would not be integer numbers but rather with decimal fractions, e.g. 0.5 pixels. In some other star image gen tools they would do a rounding, say 0.5 pixels -> 1 pixel, and then plot the star in that pixel, however this would naturally generate a small error in the attitude estimation.  While i browsed through some solutions there is this sub-pixel display method that could work out, in brief: split the one single star pixel into its peripheral pixels with some calculated grey value (could be a simulation of the effect of defocusing of the camera, in purpose), so as when processing with the image we can use some weighted center algorithm to calculate a more accurate pixel position, with decimals. 
I tried to generate a image with your project:
![image](https://github.com/user-attachments/assets/4015016a-a6cc-4984-bba8-f4340ca01af2)
And i see that one star plotted here is consisted with several pixels of different pixel values, so i am wondering if you used some algorithms to draw it this way, maybe taking into consideration of pixels with decimals? Maybe you could show me where u implemented it in the code? Thanks in advance!

**Comment by JyKlub** [comment]
ok  i kind of found it out

**Comment by markasoftware** [comment]
Having a "fractional" star position is extremely important for accurate attitude estimation. Yes, our image generator plots the stars at fractional positions and yes, it uses an algorithm to "defocus" the stars a bit so they are spread out over multiple pixels. This helps out the star identification accuracy significantly, because the centroiding algorithm can then look at the adjacent pixels to estimate the star's position much more accurately than if it was just 1 pixel.

We treat the very top-left of the image as (0,0), so the center of the top-left pixel is actually (0.5, 0.5).

We use a Gaussian distribution of brightness to the neighboring pixels, for each star. The actual distribution is called an airy disk but gaussian is a decent approximation: https://en.wikipedia.org/wiki/Airy_disk#Approximation_using_a_Gaussian_profile

To simulate the gaussian distribution, we use an oversampling approach: https://github.com/UWCubeSat/lost/blob/master/src/io.cpp#L638

Essentially we split each pixel into more pixels (I believe 4x4=16 by default?), find what the brightness would be according to the gaussian distribution at each sub-pixel, and then make the brightness of the larger pixel be the average of the brightnesses of the subpixels. The more accurate thing to do would be to calculate the actual integral of the gaussian over the pixel, which actually probably is quite doable and could be a fun addition to lost.

**Comment by markasoftware** [comment]
I just remembered why we don't do an exact integral to calculate the brightness of each pixel: We also support motion-blur, and doing the exact integral of the motion-blurred brightness over each pixel would be much harder/maybe impossible.

Also there are lots of image generation parameters that control the defocusing amount and other effects, run `lost --help` to see all of them.

**Comment by JyKlub** [comment]
> Having a "fractional" star position is extremely important for accurate attitude estimation. Yes, our image generator plots the stars at fractional positions and yes, it uses an algorithm to "defocus" the stars a bit so they are spread out over multiple pixels. This helps out the star identification accuracy significantly, because the centroiding algorithm can then look at the adjacent pixels to estimate the star's position much more accurately than if it was just 1 pixel.
> 
> We treat the very top-left of the image as (0,0), so the center of the top-left pixel is actually (0.5, 0.5).
> 
> We use a Gaussian distribution of brightness to the neighboring pixels, for each star. The actual distribution is called an airy disk but gaussian is a decent approximation: https://en.wikipedia.org/wiki/Airy_disk#Approximation_using_a_Gaussian_profile
> 
> To simulate the gaussian distribution, we use an oversampling approach: https://github.com/UWCubeSat/lost/blob/master/src/io.cpp#L638
> 
> Essentially we split each pixel into more pixels (I believe 4x4=16 by default?), find what the brightness would be according to the gaussian distribution at each sub-pixel, and then make the brightness of the larger pixel be the average of the brightnesses of the subpixels. The more accurate thing to do would be to calculate the actual integral of the gaussian over the pixel, which actually probably is quite doable and could be a fun addition to lost.

Thanks for the thorough explanation mate, was of great help! 
And yes i do see that in quite a few literatures they do this calculation with integral, i m not an expert in calculus, i m assuming it's performed by integrating the Gaussian distribution function over the square of a pixel and decide the brightness of each pixel according to that, i m not sure if i m understanding it well?  
Since i have not been doing calculus for quite a while i find it rather difficult to implement(without considering motion blur as you mentioned),  i am presuming it looks basically like this:
![image](https://github.com/user-attachments/assets/019db1bb-9998-452a-acd3-027111798339)
I think a usual approach would be switching from cartesian coord to radial coord, but have not yet found a solution yet.
Also as you ve said if using gaussian distribution without doing integral is decent enough an approximation already(any idea really how much doing an integral would enhance the accuracy?), maybe it's not necessary to tackle maths i suppose.

**Comment by JyKlub** [comment]
Oops theres this one stupid but important question i forgot to ask! 
Again with these pixel values:
![image](https://github.com/user-attachments/assets/205d91c8-f7a9-4304-9b1c-499eee46b978)
My previous doubts were, since we are using gaussian distributions here, why are the grey values here not symmetric around the "peak" value? I am guessing it's because the calculated "center" of the star is a fractional one, and i assume the pixels values would appear as symmetric when the calulated center is exactly [0.5,0,5] of a pixel, is that correct?

**Comment by markasoftware** [comment]
> Oops theres this one stupid but important question i forgot to ask! Again with these pixel values: ![image](https://private-user-images.githubusercontent.com/60698053/390951691-205d91c8-f7a9-4304-9b1c-499eee46b978.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NTE5ODAsIm5iZiI6MTczMjg1MTY4MCwicGF0aCI6Ii82MDY5ODA1My8zOTA5NTE2OTEtMjA1ZDkxYzgtZjdhOS00MzA0LTliMWMtNDk5ZWVlNDZiOTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDAzNDEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1YmQwZDExZjg2OGM2ZGIxZTA1ZWI1YzgzYmI2NTcxMjNlMzE5YjQyMWZiMWIxMWU0MTNlYzIyZmE4YzQxMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.j79hAY9CX15l-E6vwtPZFhbhy0LLO0KRMgYZGtOnr88) My previous doubts were, since we are using gaussian distributions here, why are the grey values here not symmetric around the "peak" value? I am guessing it's because the calculated "center" of the star is a fractional one, and i assume the pixels values would appear as symmetric when the calulated center is exactly [0.5,0,5] of a pixel, is that correct?

exactly, it would be symmetric around the true center.

Note that we also introduce simulated "read noise" and "shot noise" which will make it not perfectly symmetric.

There's no papers I can find specifically about image generation for star tracking, but there's a lot of good information about the general sources of noise here: https://sci-hub.se/10.1007/s40295-015-0034-4

As for the integral, your expression is correct I believe. There's no elementary closed-form solution to it, there will always be some "error function" (https://en.wikipedia.org/wiki/Error_function) in the result because integrating Gaussians is hard. I recommend using tools like Maxima or Wolfram Alpha to symbolically compute the integral instead of trying to do it on your own.

If you really do want to do the integral without a computer, your best bet is to find a paper or textbook with a "table" of common Gaussian integrals in terms of the error function and other non-elementary functions, then you can stitch these together with common integration rules (chain rule, etc) to get the closed form.

**Comment by JyKlub** [comment]
> > Oops theres this one stupid but important question i forgot to ask! Again with these pixel values: ![image](https://private-user-images.githubusercontent.com/60698053/390951691-205d91c8-f7a9-4304-9b1c-499eee46b978.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NTE5ODAsIm5iZiI6MTczMjg1MTY4MCwicGF0aCI6Ii82MDY5ODA1My8zOTA5NTE2OTEtMjA1ZDkxYzgtZjdhOS00MzA0LTliMWMtNDk5ZWVlNDZiOTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDAzNDEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1YmQwZDExZjg2OGM2ZGIxZTA1ZWI1YzgzYmI2NTcxMjNlMzE5YjQyMWZiMWIxMWU0MTNlYzIyZmE4YzQxMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.j79hAY9CX15l-E6vwtPZFhbhy0LLO0KRMgYZGtOnr88) My previous doubts were, since we are using gaussian distributions here, why are the grey values here not symmetric around the "peak" value? I am guessing it's because the calculated "center" of the star is a fractional one, and i assume the pixels values would appear as symmetric when the calulated center is exactly [0.5,0,5] of a pixel, is that correct?
> 
> exactly, it would be symmetric around the true center.
> 
> Note that we also introduce simulated "read noise" and "shot noise" which will make it not perfectly symmetric.
> 
> There's no papers I can find specifically about image generation for star tracking, but there's a lot of good information about the general sources of noise here: https://sci-hub.se/10.1007/s40295-015-0034-4
> 
> As for the integral, your expression is correct I believe. There's no elementary closed-form solution to it, there will always be some "error function" (https://en.wikipedia.org/wiki/Error_function) in the result because integrating Gaussians is hard. I recommend using tools like Maxima or Wolfram Alpha to symbolically compute the integral instead of trying to do it on your own.
> 
> If you really do want to do the integral without a computer, your best bet is to find a paper or textbook with a "table" of common Gaussian integrals in terms of the error function and other non-elementary functions, then you can stitch these together with common integration rules (chain rule, etc) to get the closed form.

Thanks a lot! Really appreciate it
